version: "3.5"
services:
  postgres:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  # This is not mandatory
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-john@test.local}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-fakepassword123!}"
    ports:
      - "16543:80"
    depends_on:
      - postgres
  # No Code Helper to generate admin or Data vizualisation
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8001:80"
      - "8002:443"
    volumes:
      - ./stacks:/appsmith-stacks
volumes:
  database-data: # named volumes can be managed easier using docker-compose
